import React, { createContext, useContext, useState, useEffect } from 'react';
import useAuthStore from '../store/authStore';

const translations = {
  tr: {
    // Navigation
    nav: {
      dashboard: 'Dashboard',
      analysis: 'Analiz',
      match: 'Eşleştirme',
      coach: 'AI Koç',
      reports: 'Raporlar',
      profile: 'Profil',
      enterprise: 'Kurumsal',
      pricing: 'Fiyatlar',
      content: 'İçerik',
      community: 'Topluluk',
      login: 'Giriş Yap',
      register: 'Ücretsiz Başla',
      logout: 'Çıkış Yap',
      enterpriseLogin: 'Kurumsal Giriş',
    },
    // Common
    common: {
      loading: 'Yükleniyor...',
      save: 'Kaydet',
      cancel: 'İptal',
      close: 'Kapat',
      confirm: 'Onayla',
      delete: 'Sil',
      edit: 'Düzenle',
      share: 'Paylaş',
      download: 'İndir',
      back: 'Geri',
      next: 'İleri',
      submit: 'Gönder',
      search: 'Ara',
      filter: 'Filtrele',
      all: 'Tümü',
      yes: 'Evet',
      no: 'Hayır',
      plan: 'Plan',
      free: 'Ücretsiz',
    },
    // Landing Page
    landing: {
      badge: '🚀 Dünyanın İlk Nörolojik Uyumluluk Platformu',
      heroLine1: 'Beynini Keşfet.',
      heroLine2: 'Potansiyelini Aç.',
      heroLine3: 'Hayatını Optimize Et.',
      heroDesc: 'Yapay zeka ve nörobilim ile kişilik profilinizi keşfedin. İş ortakları, romantik eşler ve kariyer yolunuzu bilimsel olarak belirleyin.',
      ctaStart: '🧠 Ücretsiz Analiz Başlat',
      ctaPlans: '📊 Planları Gör',
      featuresTitle: 'Neden X-Neu?',
      statsTitle: 'Rakamlarla X-Neu',
      brainTypesTitle: 'Beyin Tipini Keşfet',
      enterpriseCTA: 'Kurumsal çözümler için',
      enterpriseCTALink: 'Kurumsal sayfayı ziyaret edin →',
      footer: '© 2026 X-Neu. Tüm hakları saklıdır.',
    },
    // Dashboard
    dashboard: {
      welcome: 'Hoş geldin',
      subtitle: 'Nörolojik yolculuğuna devam et',
      startAnalysis: '🧠 Analizi Başlat',
      profileBanner: '🧠 Nörolojik Profilini Oluştur',
      profileBannerSub: '25 soruluk analizi tamamla ve beyin tipini keşfet. Sadece 10 dakika!',
      brainTypeLabel: 'Beyin Tipi',
      neuroScore: 'Nöro Skoru',
      avgMood: 'Ortalama Ruh Hali',
      avgSleep: 'Ort. Uyku',
      notDetermined: 'Belirlenmedi',
      neuroMap: '🧠 Nörolojik Harita',
      dailyCoach: '🤖 Günlük AI Koç Mesajı',
      coachWait: 'Kişiselleştirilmiş koç mesajı için önce analizini tamamla.',
      weeklyMood: '📈 Haftalık Ruh Hali & Enerji',
      quickActions: 'Hızlı Erişim',
      newAnalysis: 'Yeni Analiz',
      findMatch: 'Eşleşme Bul',
      talkCoach: 'Koçla Konuş',
      myReports: 'Raporlarım',
      checkin: 'Günlük Check-in',
      checkinTitle: '📊 Bugünkü Durumun',
      mood: 'Ruh Hali',
      energy: 'Enerji',
      stress: 'Stres',
      focus: 'Odak',
      checkinSaved: 'Check-in kaydedildi! ✅',
      notSet: '—',
      hours: 's',
      outOf: '/10',
    },
    // Brain Types
    brainTypes: {
      analytical: 'Analitik',
      creative: 'Yaratıcı',
      empathetic: 'Empatik',
      strategic: 'Stratejik',
      unknown: 'Bilinmiyor',
    },
    // Analysis Page
    analysis: {
      title: 'Nörolojik Analiz',
      subtitle: 'Beyin tipini keşfet',
      startBtn: '🚀 Analizi Başlat',
      progress: 'soru',
      of: '/',
      submitting: 'Analiz ediliyor...',
      startDesc: '25 soruluk bilimsel anket ile beyin tipinizi, enerji ritminizi, karar stilinizi ve sosyal örüntülerinizi keşfedin. Ortalama',
      startMinutes: '10 dakika',
      startMinutesSuffix: 'sürer.',
      willAnalyze: 'Analiz edilecek',
      navBack: '← Geri',
      navNext: 'İleri →',
      navAnalyze: '🧠 Analiz Et →',
      answeredOf: 'soru cevaplandı',
      errorAnswerAll: 'Lütfen tüm soruları cevaplayın',
      categoryLabels: { cognitive: 'Bilişsel', energy: 'Enerji', social: 'Sosyal', stress: 'Stres', values: 'Değerler', career: 'Kariyer' },
    },
    // Match Page
    match: {
      title: 'Eşleştirme',
      subtitle: 'Nörolojik uyumluluğunu keşfet',
      pageTitle: '💑 Nörolojik Eşleştirme',
      pageSubtitle: 'Beyin tipine göre en uyumlu kişileri keşfet',
      noProfile: 'Önce Analizini Tamamla',
      noProfileSub: 'Eşleşme özelliğini kullanmak için nörolojik analizini tamamlaman gerekiyor.',
      compatible: 'Uyumlu Kişiler',
      compatibility: 'Uyumluluk',
      viewProfile: 'Profili Gör',
      calculate: 'Hesapla',
      startAnalysis: '🧠 Analizi Başlat',
      matchTypes: {
        professional: { label: 'İş Ortağı', desc: 'En uyumlu iş ortağını bul' },
        startup: { label: 'Startup Kurucu', desc: 'Tamamlayıcı kurucu bul' },
        romantic: { label: 'Romantik', desc: 'Beyin uyumluluğuna göre partner' },
        friendship: { label: 'Arkadaşlık', desc: 'Derin arkadaşlık uyumu' },
        personal: { label: 'Kişisel', desc: 'Genel uyumluluk analizi' },
      },
      coFounder: {
        title: '🚀 Startup Kurucu Profili',
        yourBrain: 'Senin Beyin Tipin',
        recommendedRole: 'Önerilen Rol:',
        idealPairs: 'İdeal Kurucu Eşleşmeleri',
        tip: 'Kurucu İpucu',
        roles: {
          analytical: { idealRole: 'CTO / Ürün', tip: 'Sistemi sen kur, yaratıcı ortak vizyonu genişletsin.' },
          creative: { idealRole: 'CPO / Tasarım', tip: 'Ürünü sen şekillendir, analitik ortak tekniği yönetsin.' },
          empathetic: { idealRole: 'COO / Müşteri', tip: 'İnsan odaklı büyüme için stratejik kurucu gerekli.' },
          strategic: { idealRole: 'CEO / Büyüme', tip: 'Şirketi sen yönet, yaratıcı ürünü, analitik tekniği geliştirsin.' },
        },
      },
      brainLabels: { analytical: 'Analitik', creative: 'Yaratıcı', empathetic: 'Empatik', strategic: 'Stratejik' },
      loadingMatches: 'Eşleşmeler yükleniyor...',
      noMatches: 'Henüz eşleşme bulunamadı.',
      score: 'Uyum',
    },
    // Coach Page
    coach: {
      title: 'AI Koç',
      subtitle: 'Kişisel yapay zeka koçun',
      placeholder: 'Koçuna bir şey sor...',
      send: 'Gönder',
      thinking: 'Düşünüyor...',
      sidebarTitle: '🤖 AI Koçun',
      online: '● Çevrimiçi',
      description: 'Beyin tipine göre kişiselleştirilmiş, 7/24 AI koçun.',
      weekTitle: '📊 Bu Hafta',
      avgMood: 'Ort. Ruh Hali',
      avgEnergy: 'Ort. Enerji',
      avgSleep: 'Ort. Uyku',
      quickTitle: '⚡ Hızlı Sorular',
      voiceOn: '🔊 Ses Açık',
      voiceOff: '🔇 Ses Kapalı',
      stopVoice: '⏹ Durdur',
      personalizedAI: 'Kişiselleştirilmiş AI - GPT-4',
      errorResponse: 'AI koç yanıt veremedi, lütfen tekrar dene',
      quickPrompts: ['Bugün ne yapmalıyım?', 'Stresimi nasıl azaltabilirim?', 'Kariyer tavsiyesi ver', 'Sabah rutini öner', 'Daha iyi kararlar vermek için ne yapmalıyım?'],
    },
    // Reports Page
    reports: {
      title: 'Raporlarım',
      subtitle: 'Nörolojik analiz raporların',
      subtitleFull: 'Tüm nörolojik analizlerin — PDF olarak indirilebilir',
      noReports: 'Henüz rapor yok',
      noReportsSub: 'Analizi tamamla ve ilk raporunu oluştur.',
      viewReport: 'Raporu Gör',
      shareReport: 'Paylaş',
      downloadPDF: '📄 PDF İndir',
      preparing: 'Hazırlanıyor...',
      downloads: 'indirme',
      linkCopied: 'Paylaşım linki kopyalandı!',
      copyFailed: 'Link kopyalanamadı',
      startAnalysis: '🧠 Analiz Başlat',
    },
    // Profile Page
    profile: {
      title: 'Profilim',
      subtitle: 'Hesap ayarlarını yönet',
      personalInfo: 'Kişisel Bilgiler',
      name: 'İsim',
      email: 'Email',
      phone: 'Telefon',
      birthDate: 'Doğum Tarihi',
      country: 'Ülke',
      language: 'Dil',
      currentPassword: 'Mevcut Şifre',
      newPassword: 'Yeni Şifre',
      changePassword: 'Şifre Değiştir',
      saveChanges: 'Değişiklikleri Kaydet',
      subscription: 'Abonelik',
      upgradeNow: 'Şimdi Yükselt',
      male: 'Erkek',
      female: 'Kadın',
      other: 'Diğer',
      editProfile: '✏️ Profili Düzenle',
      fullName: 'Ad Soyad',
      save: 'Kaydet',
      neuroProfileSection: '🧠 Nörolojik Profil',
      brainTypeLabel: 'Beyin Tipi',
      energyRhythmLabel: 'Enerji Ritmi',
      decisionStyleLabel: 'Karar Stili',
      socialPatternLabel: 'Sosyal Örüntü',
      neuroScoreLabel: 'Nöro Skor',
      energyOptions: { morning: '🌅 Sabahçı', evening: '🌙 Akşamcı', flexible: '⚡ Esnek' },
      decisionOptions: { rational: '🎯 Rasyonel', intuitive: '✨ Sezgisel', balanced: '⚖️ Dengeli' },
      socialOptions: { introvert: '🔇 İntrovert', extrovert: '🎉 Extrovert', ambivert: '🔄 Ambivert' },
      brainTypeLabels: { analytical: 'Analitik', creative: 'Yaratıcı', empathetic: 'Empatik', strategic: 'Stratejik' },
      checkinSection: '📊 Günlük Check-in',
      moodLabel: '😊 Ruh Hali',
      energyLabel: '⚡ Enerji',
      stressLabel: '😤 Stres',
      focusLabel: '🎯 Odak',
      saveCheckin: 'Check-in Kaydet',
      sleepSection: '😴 Uyku Takibi',
      sleepDuration: 'Uyku Süresi (saat)',
      sleepQuality: 'Uyku Kalitesi',
      bedTime: 'Yatış Saati',
      wakeTime: 'Kalkış Saati',
      saveSleep: 'Uyku Kaydet',
      profileUpdated: 'Profil güncellendi',
      updateFailed: 'Güncelleme başarısız',
      checkinSaved: '✅ Günlük check-in kaydedildi',
      checkinFailed: 'Check-in kaydedilemedi',
      sleepSaved: '😴 Uyku verisi kaydedildi',
      sleepFailed: 'Uyku verisi kaydedilemedi',
    },
    // Results Page
    results: {
      loadingTitle: 'AI Analiz Yapıyor',
      loadingDesc: 'GPT-4 tabanlı nörolojik profil oluşturuluyor. Lütfen bekleyin.',
      steps: ['Anket verileri işleniyor', 'Beyin tipi tespit ediliyor', 'Profil oluşturuluyor', 'Rapor yazılıyor'],
      failedTitle: 'Analiz başarısız oldu',
      failedDesc: 'Bir hata oluştu. Lütfen tekrar dene.',
      retry: '🔄 Tekrar Dene',
      goToDashboard: '🏠 Dashboard\'a Git',
      viewReports: '📊 Raporlarımı Gör',
      findMatch: '💑 Eşleşme Bul',
      brainInfo: {
        analytical: { label: 'Analitik', desc: 'Veri odaklı, sistematik düşünür, detaylara dikkat eder.' },
        creative: { label: 'Yaratıcı', desc: 'Yenilikçi, sezgisel, büyük resmi görür.' },
        empathetic: { label: 'Empatik', desc: 'İnsan odaklı, duygusal zeka yüksek.' },
        strategic: { label: 'Stratejik', desc: 'Uzun vadeli düşünür, liderlik doğal.' },
      },
    },
    // Community Page
    community: {
      title: '🤝 Beyin Tipi Toplulukları',
      subtitle: 'Aynı beyin tipindeki insanlarla bağlan, fikir paylaş, birlikte büyü',
      sidebarTitle: '🏠 Topluluklar',
      members: 'üye',
      postPlaceholder: 'Topluluğunla bir şey paylaş... (Ctrl+Enter)',
      postBtn: 'Paylaş',
      posting: 'Paylaşılıyor...',
      loading: 'Gönderiler yükleniyor...',
      rooms: {
        analytical: { label: 'Analitik', desc: 'Veri, sistem ve mantık odaklı tartışmalar' },
        creative: { label: 'Yaratıcı', desc: 'Tasarım, sanat ve inovasyon paylaşımları' },
        empathetic: { label: 'Empatik', desc: 'İnsan ilişkileri, duygusal zeka ve bağlantı' },
        strategic: { label: 'Stratejik', desc: 'Girişimcilik, liderlik ve büyüme stratejileri' },
      },
    },
    // Content Page
    content: {
      title: '🧠 İçerik Öneri Motoru',
      subtitle: 'Beyin tipine göre seçilmiş yazılar, videolar, araçlar ve egzersizler',
      tabs: { mine: 'Benim İçin', analytical: 'Analitik', creative: 'Yaratıcı', empathetic: 'Empatik', strategic: 'Stratejik' },
      filters: { all: 'Tümü', article: 'Makale', video: 'Video', book: 'Kitap', tool: 'Araç', exercise: 'Egzersiz' },
      readBtn: 'Okumaya Başla',
      closeBtn: '✕ Kapat',
      readTime: 'okuma',
    },
    // Enterprise
    enterprise: {
      title: '🏢 Kurumsal Çözümler',
      loginTitle: '🏢 Kurumsal Panel',
      loginSubtitle: 'Kurumsal hesabınıza giriş yapın',
      loginBtn: 'Kurumsal Giriş Yap',
      noAccount: 'Hesabınız yok mu?',
      contactSales: 'Satış ekibiyle iletişime geçin',
      teamMembers: 'Ekip Üyesi',
      teamCompatibility: 'Ekip Uyumu',
      burnoutRisk: 'Burnout Riski',
      productivity: 'Üretkenlik',
      brainDistribution: '🧠 Ekip Beyin Tipi Dağılımı',
      highRisk: 'Yüksek Risk',
      features: [
        { title: 'Ekip Uyum Analizi', desc: 'Tüm ekibinizin nörolojik profillerini ve team dinamiklerini analiz edin.' },
        { title: 'Burnout Tespiti', desc: 'Erken uyarı sistemi ile çalışan tükenmişliğini önleyin.' },
        { title: 'İşe Alım Desteği', desc: 'Beyin tipi uyumuna göre ideal adayları belirleyin.' },
        { title: 'HR Dashboard', desc: 'Gerçek zamanlı ekip performans ve uyum metrikleri.' },
        { title: 'API Entegrasyonu', desc: 'Mevcut HR sistemlerinizle tam entegrasyon.' },
        { title: 'KVKK Uyumlu', desc: 'Tüm veriler KVKK ve GDPR uyumlu şekilde işlenir.' },
      ],
    },
    // Auth
    auth: {
      email: 'Email',
      password: 'Şifre',
      name: 'İsim Soyisim',
      forgotPassword: 'Şifremi unuttum',
      loginTitle: 'Hesabına giriş yap',
      registerTitle: 'Ücretsiz hesap oluştur',
      loginBtn: '🚀 Giriş Yap',
      registerBtn: '🧠 Ücretsiz Başla',
      noAccount: 'Hesabın yok mu?',
      hasAccount: 'Zaten hesabın var mı?',
      registerLink: 'Kayıt Ol',
      loginLink: 'Giriş Yap',
      agreeTerms: 'Kullanım şartlarını kabul ediyorum',
      emailPlaceholder: 'ornek@mail.com',
      passwordPlaceholder: '••••••••',
      namePlaceholder: 'Adınız Soyadınız',
    },
    // Pricing
    pricing: {
      title: 'Planlar & Fiyatlar',
      subtitle: 'Beyin tipine uygun planı seç',
      monthly: 'Aylık',
      yearly: 'Yıllık',
      save: '%20 Tasarruf',
      mostPopular: 'En Popüler',
      getStarted: 'Başla',
      currentPlan: 'Mevcut Plan',
      mo: '/ay',
      pageTitle: 'Fiyatlandırma',
      pageSubtitle: 'İhtiyacına göre plan seç. İstediğin zaman iptal et.',
      homeLink: '← Ana Sayfa',
      popular: '🔥 En Popüler',
      plans: {
        free: { name: 'Ücretsiz', cta: 'Ücretsiz Başla', features: ['Temel anket analizi', 'Beyin tipi belirleme', 'Temel rapor', 'AI koç (5 soru/gün)', 'Günlük check-in'] },
        basic: { name: 'Basic', cta: "Basic'e Geç", features: ['Tüm ücretsiz özellikler', 'Ses analizi', 'Detaylı kariyer raporu', 'AI koç sınırsız', '5 eşleştirme/ay', 'Haftalık içgörüler'] },
        premium: { name: 'Premium', cta: "Premium'a Geç", features: ['Tüm Basic özellikler', 'Yüz analizi', 'Kapsamlı nöro rapor', 'Sınırsız eşleştirme', 'İlişki haritası', 'Rapor paylaşımı', 'Öncelikli destek'] },
        enterprise: { name: 'Kurumsal', cta: 'Kurumsal Başvur', features: ['Tüm Premium özellikler', 'Ekip analizi', 'HR içgörüleri', 'Burnout tespiti', 'API erişimi', 'Özel entegrasyon', 'Dedicated manager'] },
      },
    },
  },

  // ─── ENGLISH ────────────────────────────────────────────────────────────────
  en: {
    nav: {
      dashboard: 'Dashboard',
      analysis: 'Analysis',
      match: 'Matching',
      coach: 'AI Coach',
      reports: 'Reports',
      profile: 'Profile',
      enterprise: 'Enterprise',
      pricing: 'Pricing',
      content: 'Content',
      community: 'Community',
      login: 'Sign In',
      register: 'Get Started Free',
      logout: 'Sign Out',
      enterpriseLogin: 'Enterprise Login',
    },
    common: {
      loading: 'Loading...',
      save: 'Save',
      cancel: 'Cancel',
      close: 'Close',
      confirm: 'Confirm',
      delete: 'Delete',
      edit: 'Edit',
      share: 'Share',
      download: 'Download',
      back: 'Back',
      next: 'Next',
      submit: 'Submit',
      search: 'Search',
      filter: 'Filter',
      all: 'All',
      yes: 'Yes',
      no: 'No',
      plan: 'Plan',
      free: 'Free',
    },
    landing: {
      badge: '🚀 World\'s First Neurological Compatibility Platform',
      heroLine1: 'Discover Your Brain.',
      heroLine2: 'Unlock Your Potential.',
      heroLine3: 'Optimize Your Life.',
      heroDesc: 'Discover your personality profile through AI and neuroscience. Scientifically identify business partners, romantic matches, and career paths.',
      ctaStart: '🧠 Start Free Analysis',
      ctaPlans: '📊 View Plans',
      featuresTitle: 'Why X-Neu?',
      statsTitle: 'X-Neu by the Numbers',
      brainTypesTitle: 'Discover Your Brain Type',
      enterpriseCTA: 'For enterprise solutions',
      enterpriseCTALink: 'Visit Enterprise page →',
      footer: '© 2026 X-Neu. All rights reserved.',
    },
    dashboard: {
      welcome: 'Welcome',
      subtitle: 'Continue your neurological journey',
      startAnalysis: '🧠 Start Analysis',
      profileBanner: '🧠 Create Your Neurological Profile',
      profileBannerSub: 'Complete the 25-question analysis and discover your brain type. Only 10 minutes!',
      brainTypeLabel: 'Brain Type',
      neuroScore: 'Neuro Score',
      avgMood: 'Avg. Mood',
      avgSleep: 'Avg. Sleep',
      notDetermined: 'Not Set',
      neuroMap: '🧠 Neurological Map',
      dailyCoach: '🤖 Daily AI Coach Message',
      coachWait: 'Complete your analysis first for a personalized coach message.',
      weeklyMood: '📈 Weekly Mood & Energy',
      quickActions: 'Quick Actions',
      newAnalysis: 'New Analysis',
      findMatch: 'Find Match',
      talkCoach: 'Talk to Coach',
      myReports: 'My Reports',
      checkin: 'Daily Check-in',
      checkinTitle: '📊 How Are You Today?',
      mood: 'Mood',
      energy: 'Energy',
      stress: 'Stress',
      focus: 'Focus',
      checkinSaved: 'Check-in saved! ✅',
      notSet: '—',
      hours: 'h',
      outOf: '/10',
    },
    brainTypes: {
      analytical: 'Analytical',
      creative: 'Creative',
      empathetic: 'Empathetic',
      strategic: 'Strategic',
      unknown: 'Unknown',
    },
    analysis: {
      title: 'Neurological Analysis',
      subtitle: 'Discover your brain type',
      startBtn: '🚀 Start Analysis',
      progress: 'question',
      of: '/',
      submitting: 'Analyzing...',
      startDesc: 'Discover your brain type, energy rhythm, decision style and social patterns with a 25-question scientific survey. Takes approximately',
      startMinutes: '10 minutes',
      startMinutesSuffix: '.',
      willAnalyze: 'Will analyze',
      navBack: '← Back',
      navNext: 'Next →',
      navAnalyze: '🧠 Analyze →',
      answeredOf: 'questions answered',
      errorAnswerAll: 'Please answer all questions',
      categoryLabels: { cognitive: 'Cognitive', energy: 'Energy', social: 'Social', stress: 'Stress', values: 'Values', career: 'Career' },
    },
    match: {
      title: 'Matching',
      subtitle: 'Discover your neurological compatibility',
      pageTitle: '💑 Neurological Matching',
      pageSubtitle: 'Discover the most compatible people based on your brain type',
      noProfile: 'Complete Your Analysis First',
      noProfileSub: 'You need to complete the neurological analysis to use the matching feature.',
      compatible: 'Compatible People',
      compatibility: 'Compatibility',
      viewProfile: 'View Profile',
      calculate: 'Calculate',
      startAnalysis: '🧠 Start Analysis',
      matchTypes: {
        professional: { label: 'Business Partner', desc: 'Find your most compatible business partner' },
        startup: { label: 'Co-Founder', desc: 'Find a complementary co-founder' },
        romantic: { label: 'Romantic', desc: 'Partner based on brain compatibility' },
        friendship: { label: 'Friendship', desc: 'Deep friendship compatibility' },
        personal: { label: 'Personal', desc: 'General compatibility analysis' },
      },
      coFounder: {
        title: '🚀 Startup Founder Profile',
        yourBrain: 'Your Brain Type',
        recommendedRole: 'Recommended Role:',
        idealPairs: 'Ideal Co-Founder Matches',
        tip: 'Founder Tip',
        roles: {
          analytical: { idealRole: 'CTO / Product', tip: 'You build the system, let your creative partner expand the vision.' },
          creative: { idealRole: 'CPO / Design', tip: 'You shape the product, let the analytical partner manage the tech.' },
          empathetic: { idealRole: 'COO / Customer', tip: 'Human-centered growth needs a strategic co-founder.' },
          strategic: { idealRole: 'CEO / Growth', tip: 'You lead the company, creative handles product, analytical handles tech.' },
        },
      },
      brainLabels: { analytical: 'Analytical', creative: 'Creative', empathetic: 'Empathetic', strategic: 'Strategic' },
      loadingMatches: 'Loading matches...',
      noMatches: 'No matches found yet.',
      score: 'Match',
    },
    coach: {
      title: 'AI Coach',
      subtitle: 'Your personal AI coach',
      placeholder: 'Ask your coach anything...',
      send: 'Send',
      thinking: 'Thinking...',
      sidebarTitle: '🤖 Your AI Coach',
      online: '● Online',
      description: 'Your personalized 24/7 AI coach based on your brain type.',
      weekTitle: '📊 This Week',
      avgMood: 'Avg. Mood',
      avgEnergy: 'Avg. Energy',
      avgSleep: 'Avg. Sleep',
      quickTitle: '⚡ Quick Prompts',
      voiceOn: '🔊 Voice On',
      voiceOff: '🔇 Voice Off',
      stopVoice: '⏹ Stop',
      personalizedAI: 'Personalized AI - GPT-4',
      errorResponse: 'AI coach could not respond, please try again',
      quickPrompts: ['What should I do today?', 'How can I reduce stress?', 'Give me career advice', 'Suggest a morning routine', 'How can I make better decisions?'],
    },
    reports: {
      title: 'My Reports',
      subtitle: 'Your neurological analysis reports',
      subtitleFull: 'All your neurological analyses — downloadable as PDF',
      noReports: 'No reports yet',
      noReportsSub: 'Complete an analysis and generate your first report.',
      viewReport: 'View Report',
      shareReport: 'Share',
      downloadPDF: '📄 Download PDF',
      preparing: 'Preparing...',
      downloads: 'downloads',
      linkCopied: 'Share link copied!',
      copyFailed: 'Could not copy link',
      startAnalysis: '🧠 Start Analysis',
    },
    profile: {
      title: 'My Profile',
      subtitle: 'Manage your account settings',
      personalInfo: 'Personal Information',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      birthDate: 'Birth Date',
      country: 'Country',
      language: 'Language',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      changePassword: 'Change Password',
      saveChanges: 'Save Changes',
      subscription: 'Subscription',
      upgradeNow: 'Upgrade Now',
      male: 'Male',
      female: 'Female',
      other: 'Other',
      editProfile: '✏️ Edit Profile',
      fullName: 'Full Name',
      save: 'Save',
      neuroProfileSection: '🧠 Neurological Profile',
      brainTypeLabel: 'Brain Type',
      energyRhythmLabel: 'Energy Rhythm',
      decisionStyleLabel: 'Decision Style',
      socialPatternLabel: 'Social Pattern',
      neuroScoreLabel: 'Neuro Score',
      energyOptions: { morning: '🌅 Morning Person', evening: '🌙 Night Owl', flexible: '⚡ Flexible' },
      decisionOptions: { rational: '🎯 Rational', intuitive: '✨ Intuitive', balanced: '⚖️ Balanced' },
      socialOptions: { introvert: '🔇 Introvert', extrovert: '🎉 Extrovert', ambivert: '🔄 Ambivert' },
      brainTypeLabels: { analytical: 'Analytical', creative: 'Creative', empathetic: 'Empathetic', strategic: 'Strategic' },
      checkinSection: '📊 Daily Check-in',
      moodLabel: '😊 Mood',
      energyLabel: '⚡ Energy',
      stressLabel: '😤 Stress',
      focusLabel: '🎯 Focus',
      saveCheckin: 'Save Check-in',
      sleepSection: '😴 Sleep Tracker',
      sleepDuration: 'Sleep Duration (hours)',
      sleepQuality: 'Sleep Quality',
      bedTime: 'Bedtime',
      wakeTime: 'Wake Time',
      saveSleep: 'Save Sleep',
      profileUpdated: 'Profile updated',
      updateFailed: 'Update failed',
      checkinSaved: '✅ Daily check-in saved',
      checkinFailed: 'Check-in could not be saved',
      sleepSaved: '😴 Sleep data saved',
      sleepFailed: 'Sleep data could not be saved',
    },
    // Results Page
    results: {
      loadingTitle: 'AI Analyzing',
      loadingDesc: 'Creating your GPT-4 based neurological profile. Please wait.',
      steps: ['Processing survey data', 'Detecting brain type', 'Building profile', 'Writing report'],
      failedTitle: 'Analysis failed',
      failedDesc: 'An error occurred. Please try again.',
      retry: '🔄 Try Again',
      goToDashboard: '🏠 Go to Dashboard',
      viewReports: '📊 View My Reports',
      findMatch: '💑 Find a Match',
      brainInfo: {
        analytical: { label: 'Analytical', desc: 'Data-driven, systematic thinker, pays attention to detail.' },
        creative: { label: 'Creative', desc: 'Innovative, intuitive, sees the big picture.' },
        empathetic: { label: 'Empathetic', desc: 'People-oriented, high emotional intelligence.' },
        strategic: { label: 'Strategic', desc: 'Long-term thinker, natural leader.' },
      },
    },
    // Community Page
    community: {
      title: '🤝 Brain Type Communities',
      subtitle: 'Connect with people who share your brain type, share ideas, grow together',
      sidebarTitle: '🏠 Communities',
      members: 'members',
      postPlaceholder: 'Share something with your community... (Ctrl+Enter)',
      postBtn: 'Post',
      posting: 'Posting...',
      loading: 'Loading posts...',
      rooms: {
        analytical: { label: 'Analytical', desc: 'Data, systems and logic-focused discussions' },
        creative: { label: 'Creative', desc: 'Design, art and innovation sharing' },
        empathetic: { label: 'Empathetic', desc: 'Human relationships, emotional intelligence & connection' },
        strategic: { label: 'Strategic', desc: 'Entrepreneurship, leadership and growth strategies' },
      },
    },
    // Content Page
    content: {
      title: '🧠 Content Recommendation Engine',
      subtitle: 'Articles, videos, tools and exercises curated for your brain type',
      tabs: { mine: 'For Me', analytical: 'Analytical', creative: 'Creative', empathetic: 'Empathetic', strategic: 'Strategic' },
      filters: { all: 'All', article: 'Article', video: 'Video', book: 'Book', tool: 'Tool', exercise: 'Exercise' },
      readBtn: 'Start Reading',
      closeBtn: '✕ Close',
      readTime: 'read',
    },
    enterprise: {
      title: '🏢 Enterprise Solutions',
      loginTitle: '🏢 Enterprise Panel',
      loginSubtitle: 'Sign in to your enterprise account',
      loginBtn: 'Enterprise Sign In',
      noAccount: "Don't have an account?",
      contactSales: 'Contact our sales team',
      teamMembers: 'Team Members',
      teamCompatibility: 'Team Compatibility',
      burnoutRisk: 'Burnout Risk',
      productivity: 'Productivity',
      brainDistribution: '🧠 Team Brain Type Distribution',
      highRisk: 'High Risk',
      features: [
        { title: 'Team Compatibility Analysis', desc: 'Analyze the neurological profiles and team dynamics of your entire team.' },
        { title: 'Burnout Detection', desc: 'Prevent employee burnout with an early warning system.' },
        { title: 'Recruitment Support', desc: 'Identify ideal candidates based on brain type compatibility.' },
        { title: 'HR Dashboard', desc: 'Real-time team performance and compatibility metrics.' },
        { title: 'API Integration', desc: 'Full integration with your existing HR systems.' },
        { title: 'GDPR Compliant', desc: 'All data is processed in compliance with GDPR.' },
      ],
    },
    auth: {
      email: 'Email',
      password: 'Password',
      name: 'Full Name',
      forgotPassword: 'Forgot password',
      loginTitle: 'Sign in to your account',
      registerTitle: 'Create a free account',
      loginBtn: '🚀 Sign In',
      registerBtn: '🧠 Get Started Free',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      registerLink: 'Register',
      loginLink: 'Sign In',
      agreeTerms: 'I agree to the terms of service',
      emailPlaceholder: 'example@mail.com',
      passwordPlaceholder: '••••••••',
      namePlaceholder: 'Your Full Name',
    },
    pricing: {
      title: 'Plans & Pricing',
      subtitle: 'Choose the plan for your brain type',
      monthly: 'Monthly',
      yearly: 'Yearly',
      save: '20% Off',
      mostPopular: 'Most Popular',
      getStarted: 'Get Started',
      currentPlan: 'Current Plan',
      mo: '/mo',
      pageTitle: 'Pricing',
      pageSubtitle: 'Choose the plan that fits your needs. Cancel anytime.',
      homeLink: '← Home',
      popular: '🔥 Most Popular',
      plans: {
        free: { name: 'Free', cta: 'Get Started Free', features: ['Basic survey analysis', 'Brain type identification', 'Basic report', 'AI coach (5 questions/day)', 'Daily check-in'] },
        basic: { name: 'Basic', cta: 'Get Basic', features: ['All free features', 'Voice analysis', 'Detailed career report', 'Unlimited AI coach', '5 matches/month', 'Weekly insights'] },
        premium: { name: 'Premium', cta: 'Get Premium', features: ['All Basic features', 'Face analysis', 'Comprehensive neuro report', 'Unlimited matching', 'Relationship map', 'Report sharing', 'Priority support'] },
        enterprise: { name: 'Enterprise', cta: 'Apply for Enterprise', features: ['All Premium features', 'Team analysis', 'HR insights', 'Burnout detection', 'API access', 'Custom integration', 'Dedicated manager'] },
      },
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const { user } = useAuthStore();
  // Initialize from user preference → localStorage → default 'tr'
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('neuro-lang') || user?.language || 'tr';
  });

  // Sync when user's stored language changes
  useEffect(() => {
    if (user?.language && user.language !== lang) {
      setLangState(user.language);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user?.language]);

  const setLang = (l) => {
    setLangState(l);
    localStorage.setItem('neuro-lang', l);
  };

  const t = translations[lang] || translations.tr;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}

export default LanguageContext;
